language: java
install: mvn install
jdk:
- openjdk11
services:
- postgresql
before_install:
- psql -c 'create database softensy;' -U postgres
addons:
  sonarcloud:
    organization: "gaydukov"
    token:
      secure: "pTV+d5/96e9u+L41mGZmohk02cz0k47DZuwaRU5HvZaLzEQACixfhy3p+opj0eQuxKuDkRhD855B70gTKkCwv5M9tLpt/lY7jkFNlIfaTV3s9EG2dI2f/2OQFumV56nCN1UuMOEj/1P/iV2U5ZQrxoYrNBOJxbGcHzEx9w7IcgawQNWx4ALrS4n0MGpzFrbhVH5Rj9EbAofjcxRPPaepDaEW8q62e0jq855nODoX+bDZNWYeOBJ9WYnTlIyMmPbPKwPYmGO6U5X6lI4I3Q7t2iHY6EyHXYqwNkv1LOUZEjtiCZalqr41OAOkrve+OCDWugfd6opag9r9vqRUuA1FdOry/gaDhpFpi2pccOqILB+O0VTYzKdczw72IW2JjwkaGBOKhKzr2ewUj87e93dNx09sAllnoaCefvPFZikYcqNmhWOzJiNp0dEI+lPgTS3BkO1uTzvlccK7MC/gJBsu4d2W8kzu0jMcTZVBxXwv4FIplaJjwveaca1WszbyL5DeKlygVBODYIiNLTuh4n/TG8TKTns7mSsJZqJoXO57dKuh8wnGPfBCGNo8gUhbka+kNRh/uEA9GxxPAQ/YiZfhF7aVSPP+xbc4fSjF1QzSkgomrX+cgd85N5SE+y2Dyd1U5KpUH9g/z0iszzDtgYvZUCe4EZhfM3LNi0O2MAHbISs="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gaydukov_SoftensySpringBoot
